### ISSUE TITLE
Log is not working properly in Windows prompt

### ISSUE THREAD

**Issue by cyChop** [alcibiade/pan-discovery#4]
The animation appender (replacing last line) seems not to be working in Windows 10's command prompt. It works fine in MSYS and PowerShell, though.

### Command Prompt

![Windows prompt](https://cloud.githubusercontent.com/assets/1841583/26561287/6c35d87c-44bd-11e7-9772-a70d8f7d2fab.png)

### PowerShell

![PowerShell](https://cloud.githubusercontent.com/assets/1841583/26561295/7d81101a-44bd-11e7-9be5-dac27d972ef3.png)

### MSYS

![MSYS](https://cloud.githubusercontent.com/assets/1841583/26561294/77f247b8-44bd-11e7-9928-609f7b6879ad.png)

**Comment by alcibiade** [comment]
I have made a fix to detect TERM environment variable. It may have simply fixed the issue on non-ansi displays.

@cyChop can you confirm corresponding values (or absence of value) for the TERM environment variable in the different contexts ?

**Comment by cyChop** [comment]
PowerShell now behaves like Command Prompt, but everything looks fine otherwise.

![image](https://cloud.githubusercontent.com/assets/1841583/26742383/c1be2e5c-47dd-11e7-98e1-d58f6b423a20.png)
![image](https://cloud.githubusercontent.com/assets/1841583/26742387/c5012ac4-47dd-11e7-9f1a-7dc07d8bab9e.png)
![image](https://cloud.githubusercontent.com/assets/1841583/26742396/ca64421c-47dd-11e7-9efd-74150b1fb98b.png)

**Comment by alcibiade** [comment]
Thanks !
